<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.7">
  <POU Name="Controller_PRG" Id="{d7ffc0b2-bea9-4071-b871-ad534ffebbe7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Controller_PRG
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Controller_PRG">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>